const keys = ['title','sandbox','brief','seconds','ratio','quote','price','pay','confirm','edit','newOrder','close','error','unconfigured','notApproved','quoted','awaitingApproval','paid','pricing','privacy'];
const rows = {
 en:['Video commission','PayPal sandbox · test funds only','Editing brief','Target seconds','Aspect ratio','Create quote','Quote','Approve in PayPal','Verify payment','Open editing assistant','New commission','Close','Request failed. Retry safely.','Configure PayPal sandbox credentials on the server.','Payment is not approved. Complete PayPal approval first.','Quoted','Awaiting approval','Payment verified','Fixed pricing: $10 + $5 per started 15 seconds. AI does not set prices.','Brief and order details are stored on this local server. Media stays in your browser. Delivery is manual; no customer portal yet.'],
 zh:['视频接单','PayPal 沙盒 · 仅测试资金','剪辑需求','目标秒数','画面比例','生成报价','报价','前往 PayPal 确认','核验付款','打开剪辑助手','新建需求','关闭','请求失败，可安全重试。','请在服务端配置 PayPal 沙盒凭证。','尚未授权付款，请先在 PayPal 完成确认。','已报价','等待付款确认','付款已核验','固定规则：10 美元基础价，每开始 15 秒加 5 美元。AI 不决定价格。','需求与订单保存在本地服务端，素材保留在浏览器中。当前手动交付，尚无客户门户。'],
 ja:['動画制作依頼','PayPal サンドボックス · テスト資金のみ','編集内容','目標秒数','画面比率','見積もり作成','見積もり','PayPal で承認','支払い確認','編集アシスタントを開く','新規依頼','閉じる','失敗しました。再試行できます。','サーバーにサンドボックス認証情報を設定してください。','先に PayPal で承認してください。','見積もり済み','承認待ち','支払い確認済み','固定料金：10ドル＋15秒ごとに5ドル（切り上げ）。AI は価格を決めません。','依頼と注文はローカルサーバー、素材はブラウザーに保存。納品は手動で、顧客ポータルは未実装です。'],
 ko:['영상 제작 의뢰','PayPal 샌드박스 · 테스트 자금 전용','편집 요청','목표 초','화면 비율','견적 생성','견적','PayPal에서 승인','결제 확인','편집 도우미 열기','새 의뢰','닫기','요청 실패. 다시 시도하세요.','서버에 샌드박스 인증 정보를 설정하세요.','먼저 PayPal에서 승인하세요.','견적 완료','승인 대기','결제 검증 완료','고정 요금: $10 + 시작된 15초당 $5. AI는 가격을 정하지 않습니다.','의뢰와 주문은 로컬 서버에, 미디어는 브라우저에 저장됩니다. 수동 납품이며 고객 포털은 없습니다.'],
 es:['Encargo de vídeo','Sandbox PayPal · solo fondos de prueba','Solicitud de edición','Segundos objetivo','Proporción','Crear presupuesto','Presupuesto','Aprobar en PayPal','Verificar pago','Abrir asistente','Nuevo encargo','Cerrar','Error. Puedes reintentar.','Configura las credenciales sandbox en el servidor.','Aprueba primero en PayPal.','Presupuestado','Pendiente de aprobación','Pago verificado','Precio fijo: $10 + $5 por cada 15 s iniciados. La IA no fija precios.','Solicitud y pedido en el servidor local; medios en el navegador. Entrega manual, sin portal de clientes.'],
 fr:['Commande vidéo','Sandbox PayPal · fonds de test uniquement','Demande de montage','Durée en secondes','Format','Créer un devis','Devis','Approuver sur PayPal','Vérifier le paiement','Ouvrir l’assistant','Nouvelle commande','Fermer','Échec. Réessayez.','Configurez les identifiants sandbox côté serveur.','Approuvez d’abord sur PayPal.','Devis créé','Approbation en attente','Paiement vérifié','Tarif fixe : 10 $ + 5 $ par tranche de 15 s entamée. L’IA ne fixe pas les prix.','Demande et commande sur le serveur local ; médias dans le navigateur. Livraison manuelle, sans portail client.'],
 de:['Videoauftrag','PayPal-Sandbox · nur Testgeld','Schnittauftrag','Zieldauer in Sekunden','Seitenverhältnis','Angebot erstellen','Angebot','Bei PayPal bestätigen','Zahlung prüfen','Assistent öffnen','Neuer Auftrag','Schließen','Fehlgeschlagen. Erneut versuchen.','Sandbox-Zugangsdaten am Server konfigurieren.','Zuerst bei PayPal bestätigen.','Angebot erstellt','Bestätigung ausstehend','Zahlung geprüft','Festpreis: 10 $ + 5 $ je angefangene 15 Sekunden. KI bestimmt keine Preise.','Auftrag auf lokalem Server, Medien im Browser. Manuelle Lieferung, noch kein Kundenportal.'],
 pt:['Encomenda de vídeo','Sandbox PayPal · apenas saldo de teste','Pedido de edição','Segundos desejados','Proporção','Criar orçamento','Orçamento','Aprovar no PayPal','Verificar pagamento','Abrir assistente','Novo pedido','Fechar','Falha. Tente novamente.','Configure as credenciais sandbox no servidor.','Aprove primeiro no PayPal.','Orçamento criado','Aguardando aprovação','Pagamento verificado','Preço fixo: US$10 + US$5 por cada 15 s iniciados. A IA não define preços.','Pedido no servidor local; mídia no navegador. Entrega manual, sem portal do cliente.'],
 th:['งานตัดต่อวิดีโอ','PayPal sandbox · เงินทดสอบเท่านั้น','คำขอตัดต่อ','ระยะเวลาเป็นวินาที','อัตราส่วน','สร้างใบเสนอราคา','ราคา','อนุมัติใน PayPal','ตรวจสอบการชำระเงิน','เปิดผู้ช่วยตัดต่อ','งานใหม่','ปิด','คำขอล้มเหลว ลองอีกครั้งได้','ตั้งค่าข้อมูล sandbox บนเซิร์ฟเวอร์','โปรดอนุมัติใน PayPal ก่อน','เสนอราคาแล้ว','รออนุมัติ','ยืนยันการชำระเงินแล้ว','ราคาคงที่ $10 และ $5 ต่อช่วง 15 วินาทีที่เริ่มใช้ AI ไม่กำหนดราคา','เก็บคำขอและคำสั่งซื้อบนเซิร์ฟเวอร์ในเครื่อง สื่ออยู่ในเบราว์เซอร์ ส่งงานด้วยตนเอง ยังไม่มีพอร์ทัลลูกค้า'],
 vi:['Đặt dựng video','PayPal sandbox · chỉ tiền thử nghiệm','Yêu cầu dựng','Số giây mục tiêu','Tỷ lệ','Tạo báo giá','Báo giá','Duyệt trên PayPal','Xác minh thanh toán','Mở trợ lý dựng','Yêu cầu mới','Đóng','Thất bại. Hãy thử lại.','Cấu hình thông tin sandbox trên máy chủ.','Duyệt trên PayPal trước.','Đã báo giá','Chờ duyệt','Đã xác minh thanh toán','Giá cố định: $10 + $5 mỗi 15 giây bắt đầu. AI không quyết định giá.','Yêu cầu và đơn lưu trên máy chủ cục bộ; tư liệu ở trình duyệt. Giao thủ công, chưa có cổng khách hàng.'],
 ru:['Заказ видео','Песочница PayPal · только тестовые средства','Задание на монтаж','Длительность в секундах','Формат','Создать смету','Смета','Подтвердить в PayPal','Проверить оплату','Открыть помощника','Новый заказ','Закрыть','Ошибка. Повторите запрос.','Настройте ключи песочницы на сервере.','Сначала подтвердите в PayPal.','Смета готова','Ожидает подтверждения','Оплата проверена','Фиксированная цена: $10 + $5 за каждые начатые 15 с. ИИ не назначает цены.','Задание и заказ на локальном сервере, медиа в браузере. Ручная передача, портала клиента пока нет.'],
 it:['Commissione video','Sandbox PayPal · solo fondi di prova','Richiesta di montaggio','Secondi desiderati','Proporzioni','Crea preventivo','Preventivo','Approva su PayPal','Verifica pagamento','Apri assistente','Nuova richiesta','Chiudi','Errore. Riprova.','Configura le credenziali sandbox sul server.','Approva prima su PayPal.','Preventivo pronto','In attesa di approvazione','Pagamento verificato','Prezzo fisso: $10 + $5 per ogni 15 s iniziati. L’IA non stabilisce prezzi.','Richiesta e ordine sul server locale; media nel browser. Consegna manuale, nessun portale clienti.'],
 id:['Pesanan video','Sandbox PayPal · hanya dana uji','Permintaan penyuntingan','Target detik','Rasio','Buat penawaran','Penawaran','Setujui di PayPal','Verifikasi pembayaran','Buka asisten','Pesanan baru','Tutup','Gagal. Silakan coba lagi.','Atur kredensial sandbox di server.','Setujui di PayPal terlebih dahulu.','Ditawarkan','Menunggu persetujuan','Pembayaran terverifikasi','Harga tetap: $10 + $5 per 15 detik yang dimulai. AI tidak menentukan harga.','Permintaan dan pesanan di server lokal; media di browser. Penyerahan manual, belum ada portal pelanggan.'],
};
export function paypalCopy(language) { const key = String(language).toLowerCase().split(/[-_]/)[0]; return Object.fromEntries(keys.map((name, i) => [name, (rows[key] || rows.en)[i]])); }
