const keys = ['title','choose','upload','download','ready','privacy','invalidVideo','tooLarge','alreadyDelivered','notDelivered'];
const rows = {
 en:['Video delivery','Choose exported video','Attach delivery','Download delivery','Ready to download','Attach an MP4 or WebM up to 64 MiB. This copies the file to the local server. One final file per order; no public sharing link.','Choose a playable MP4 or WebM.','Maximum file size is 64 MiB.','This order already has a different final file.','No delivery is available yet.'],
 zh:['成片交付','选择已导出视频','附上交付文件','下载交付文件','可下载','支持 64 MiB 以内的 MP4 或 WebM，文件会复制到本地服务端。每笔订单附一份最终成片，暂无公开分享链接。','请选择可播放的 MP4 或 WebM。','文件不能超过 64 MiB。','该订单已有另一份最终成片。','尚无交付文件。'],
 ja:['動画納品','書き出した動画を選択','納品ファイルを添付','納品をダウンロード','ダウンロード可能','64 MiB 以下の MP4/WebM をローカルサーバーへコピー。注文ごとに最終動画1本。公開リンクはありません。','再生できる MP4/WebM を選択してください。','上限は64 MiBです。','この注文には別の最終動画があります。','納品ファイルはまだありません。'],
 ko:['영상 납품','내보낸 영상 선택','납품 파일 첨부','납품 다운로드','다운로드 가능','64 MiB 이하 MP4/WebM을 로컬 서버에 복사합니다. 주문당 최종 영상 하나이며 공개 링크는 없습니다.','재생 가능한 MP4/WebM을 선택하세요.','최대 크기는 64 MiB입니다.','이미 다른 최종 영상이 있습니다.','아직 납품 파일이 없습니다.'],
 es:['Entrega de vídeo','Elegir vídeo exportado','Adjuntar entrega','Descargar entrega','Disponible','MP4/WebM hasta 64 MiB, copiado al servidor local. Un vídeo final por pedido; sin enlace público.','Elige un MP4/WebM reproducible.','Máximo 64 MiB.','Ya existe otro vídeo final.','Todavía no hay entrega.'],
 fr:['Livraison vidéo','Choisir la vidéo exportée','Joindre la livraison','Télécharger la livraison','Disponible','MP4/WebM de 64 Mio maximum, copié sur le serveur local. Une vidéo finale par commande, sans lien public.','Choisissez un MP4/WebM lisible.','Maximum 64 Mio.','Une autre vidéo finale existe déjà.','Aucune livraison disponible.'],
 de:['Videolieferung','Exportiertes Video wählen','Lieferung anhängen','Lieferung herunterladen','Verfügbar','MP4/WebM bis 64 MiB wird auf den lokalen Server kopiert. Ein finales Video pro Auftrag, kein öffentlicher Link.','Abspielbares MP4/WebM wählen.','Maximal 64 MiB.','Ein anderes finales Video ist bereits vorhanden.','Noch keine Lieferung verfügbar.'],
 pt:['Entrega do vídeo','Escolher vídeo exportado','Anexar entrega','Baixar entrega','Disponível','MP4/WebM até 64 MiB copiado ao servidor local. Um vídeo final por pedido, sem link público.','Escolha um MP4/WebM reproduzível.','Máximo de 64 MiB.','Outro vídeo final já foi anexado.','Ainda não há entrega.'],
 th:['ส่งมอบวิดีโอ','เลือกวิดีโอที่ส่งออก','แนบไฟล์ส่งมอบ','ดาวน์โหลดไฟล์','พร้อมดาวน์โหลด','MP4/WebM ไม่เกิน 64 MiB จะคัดลอกไปยังเซิร์ฟเวอร์ในเครื่อง หนึ่งวิดีโอสุดท้ายต่อคำสั่งซื้อ ไม่มีลิงก์สาธารณะ','เลือก MP4/WebM ที่เล่นได้','ขนาดสูงสุด 64 MiB','มีวิดีโอสุดท้ายอื่นแล้ว','ยังไม่มีไฟล์ส่งมอบ'],
 vi:['Giao video','Chọn video đã xuất','Đính kèm bản giao','Tải bản giao','Sẵn sàng tải','MP4/WebM tối đa 64 MiB, sao chép lên máy chủ cục bộ. Mỗi đơn một video cuối, không có liên kết công khai.','Chọn MP4/WebM phát được.','Tối đa 64 MiB.','Đã có video cuối khác.','Chưa có bản giao.'],
 ru:['Передача видео','Выбрать экспортированное видео','Прикрепить результат','Скачать результат','Доступно для скачивания','MP4/WebM до 64 МиБ копируется на локальный сервер. Один итоговый файл на заказ, без публичной ссылки.','Выберите воспроизводимый MP4/WebM.','Максимум 64 МиБ.','Другой итоговый файл уже прикреплён.','Результат пока недоступен.'],
 it:['Consegna video','Scegli video esportato','Allega consegna','Scarica consegna','Disponibile','MP4/WebM fino a 64 MiB, copiato sul server locale. Un video finale per ordine, senza link pubblico.','Scegli un MP4/WebM riproducibile.','Massimo 64 MiB.','È già presente un altro video finale.','Nessuna consegna disponibile.'],
 id:['Penyerahan video','Pilih video hasil ekspor','Lampirkan hasil','Unduh hasil','Siap diunduh','MP4/WebM hingga 64 MiB disalin ke server lokal. Satu video final per pesanan, tanpa tautan publik.','Pilih MP4/WebM yang dapat diputar.','Maksimum 64 MiB.','Video final lain sudah dilampirkan.','Belum ada hasil tersedia.'],
};
export function deliveryCopy(language) { const row = rows[String(language).toLowerCase().split(/[-_]/)[0]] || rows.en; return Object.fromEntries(keys.map((k,i)=>[k,row[i]])); }
