const keys = ["Title","Description","Enable","Ready","Position","Drag","Horizontal","Vertical","Strength","Color","Warm","Neutral","Cool","Range","Softness","Advanced","Compare","Original","Reset","AnalyzeHint","QualityHint"];
const rows = {
 zh: ["视频打光","根据场景深度调整局部光照。","启用打光","深度已就绪","灯位","拖动调整灯位","水平","垂直","强度","光色","暖色","中性","冷色","范围","柔和度","高级设置","按住查看原图","正在查看原图","重置","先分析场景深度，再调整打光。","更改分析质量后，需要重新分析。"],
 en: ["Video relighting","Adjust local lighting using scene depth.","Enable lighting","Depth ready","Light position","Drag to position the light","Horizontal","Vertical","Intensity","Light color","Warm","Neutral","Cool","Range","Softness","Advanced","Hold to view original","Viewing original","Reset","Analyze scene depth before adjusting lighting.","Changing analysis quality requires a new analysis."],
 ja: ["動画ライティング","シーンの深度で局所照明を調整。","照明を有効化","深度準備完了","ライト位置","ドラッグでライトを移動","水平","垂直","強度","光の色","暖色","中性","寒色","範囲","柔らかさ","詳細設定","長押しで元画像","元画像を表示中","リセット","照明の調整前にシーンの深度を解析してください。","解析品質を変えると再解析が必要です。"],
 ko: ["영상 조명","장면 깊이로 부분 조명을 조절합니다.","조명 사용","깊이 준비 완료","조명 위치","드래그하여 조명 이동","수평","수직","강도","조명 색","따뜻함","중립","차가움","범위","부드러움","고급 설정","누르고 원본 보기","원본 보는 중","초기화","조명을 조절하기 전에 장면 깊이를 분석하세요.","분석 품질을 바꾸면 다시 분석해야 합니다."],
 es: ["Iluminación de vídeo","Ajusta la luz local según la profundidad.","Activar luz","Profundidad lista","Posición de luz","Arrastra para mover la luz","Horizontal","Vertical","Intensidad","Color de luz","Cálido","Neutro","Frío","Alcance","Suavidad","Avanzado","Mantén para ver original","Viendo original","Restablecer","Analiza la profundidad antes de ajustar la luz.","Cambiar la calidad requiere otro análisis."],
 fr: ["Éclairage vidéo","Ajustez la lumière locale selon la profondeur.","Activer l’éclairage","Profondeur prête","Position de lumière","Glissez pour déplacer la lumière","Horizontal","Vertical","Intensité","Couleur","Chaud","Neutre","Froid","Portée","Douceur","Réglages avancés","Maintenir pour voir l’original","Original affiché","Réinitialiser","Analysez la profondeur avant de régler la lumière.","Changer la qualité nécessite une nouvelle analyse."],
 de: ["Videobeleuchtung","Lokales Licht anhand der Szenentiefe anpassen.","Licht aktivieren","Tiefe bereit","Lichtposition","Ziehen, um das Licht zu bewegen","Horizontal","Vertikal","Stärke","Lichtfarbe","Warm","Neutral","Kühl","Reichweite","Weichheit","Erweitert","Halten für Original","Original wird angezeigt","Zurücksetzen","Vor der Lichtanpassung die Szenentiefe analysieren.","Eine neue Qualität erfordert eine erneute Analyse."],
 pt: ["Iluminação de vídeo","Ajuste a luz local pela profundidade da cena.","Ativar luz","Profundidade pronta","Posição da luz","Arraste para mover a luz","Horizontal","Vertical","Intensidade","Cor da luz","Quente","Neutra","Fria","Alcance","Suavidade","Avançado","Segure para ver original","Exibindo original","Redefinir","Analise a profundidade antes de ajustar a luz.","Mudar a qualidade exige nova análise."],
 th: ["จัดแสงวิดีโอ","ปรับแสงเฉพาะส่วนตามความลึกของฉาก","เปิดใช้แสง","ความลึกพร้อมแล้ว","ตำแหน่งแสง","ลากเพื่อย้ายแสง","แนวนอน","แนวตั้ง","ความเข้ม","สีแสง","อุ่น","กลาง","เย็น","ระยะ","ความนุ่ม","ขั้นสูง","กดค้างเพื่อดูต้นฉบับ","กำลังดูต้นฉบับ","รีเซ็ต","วิเคราะห์ความลึกของฉากก่อนปรับแสง","เมื่อเปลี่ยนคุณภาพต้องวิเคราะห์ใหม่"],
 vi: ["Chiếu sáng video","Chỉnh ánh sáng cục bộ theo độ sâu cảnh.","Bật ánh sáng","Độ sâu sẵn sàng","Vị trí đèn","Kéo để di chuyển đèn","Ngang","Dọc","Cường độ","Màu ánh sáng","Ấm","Trung tính","Lạnh","Phạm vi","Độ mềm","Nâng cao","Giữ để xem bản gốc","Đang xem bản gốc","Đặt lại","Phân tích độ sâu trước khi chỉnh ánh sáng.","Đổi chất lượng cần phân tích lại."],
 ru: ["Освещение видео","Локальный свет с учётом глубины сцены.","Включить свет","Глубина готова","Положение света","Перетащите источник света","По горизонтали","По вертикали","Интенсивность","Цвет света","Тёплый","Нейтральный","Холодный","Радиус","Мягкость","Дополнительно","Удерживать для оригинала","Показан оригинал","Сбросить","Перед настройкой света проанализируйте глубину.","Изменение качества требует нового анализа."],
 it: ["Illuminazione video","Regola la luce locale in base alla profondità.","Attiva luce","Profondità pronta","Posizione luce","Trascina per spostare la luce","Orizzontale","Verticale","Intensità","Colore luce","Caldo","Neutro","Freddo","Raggio","Morbidezza","Avanzate","Tieni premuto per l’originale","Originale visibile","Ripristina","Analizza la profondità prima di regolare la luce.","Cambiare qualità richiede una nuova analisi."],
 id: ["Pencahayaan video","Atur cahaya lokal berdasarkan kedalaman adegan.","Aktifkan cahaya","Kedalaman siap","Posisi cahaya","Seret untuk memindahkan cahaya","Horizontal","Vertikal","Intensitas","Warna cahaya","Hangat","Netral","Dingin","Jangkauan","Kelembutan","Lanjutan","Tahan untuk melihat asli","Menampilkan asli","Atur ulang","Analisis kedalaman sebelum mengatur cahaya.","Mengubah kualitas memerlukan analisis ulang."],
};
export const RELIGHTING_COPY = Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(keys.map((key, index) => [`relight${key}`, row[index]]))]));

const distances = { zh:"灯光距离", en:"Light distance", ja:"ライトの距離", ko:"조명 거리", es:"Distancia de luz", fr:"Distance de lumière", de:"Lichtabstand", pt:"Distância da luz", th:"ระยะห่างแสง", vi:"Khoảng cách đèn", ru:"Расстояние до света", it:"Distanza luce", id:"Jarak cahaya" };
Object.entries(distances).forEach(([language, text]) => { RELIGHTING_COPY[language].relightDistance = text; });
