const keys = ["title", "badge", "intro", "local", "cloud", "prompt", "send", "privacy", "review", "applied", "help", "cloudError", "token", "consent"];
const rows = {
  en: ["Editing assistant", "Alexa+ experience · simulation", "Describe an edit, review the changes, then keep creating on the same timeline.", "Local commands", "AI planning", "What would you like to change?", "Review edit", "Media stays in this browser. AI planning sends your conversation and clip metadata to the configured model service.", "Your edit is ready for review. Apply it in the review panel to update the timeline.", "Applied to the timeline. You can preview, continue editing, or export from the top bar.", "Local commands: 9:16 · trim first 3s · music 20% · last first. Trimming needs a simple 1× video; music needs an existing music clip; reordering needs two clips.", "AI planning is unavailable. Check the server connection and access code, or choose local commands.", "Access code (if required)", "Send conversation and clip metadata for AI planning"],
  zh: ["剪辑助手", "Alexa+ 体验 · 模拟", "描述修改，审核变化，再在同一条时间线上继续创作。", "本地指令", "AI 规划", "你想怎样修改？", "审核修改", "素材保留在浏览器中。AI 规划会将对话和片段元数据发送到配置的模型服务。", "修改方案已准备好，请在审核面板中应用到时间线。", "已应用到时间线。你可以预览、继续修改，或通过顶部按钮导出。", "本地指令：9:16 · 首段 3秒 · 音乐 20% · 末段移到开头。裁剪需要普通 1× 视频；音乐需要已有音乐片段；排序需要两个片段。", "AI 规划暂不可用，请检查服务连接与访问码，或使用本地指令。", "访问码（如需）", "发送对话与片段元数据用于 AI 规划"],
  ja: ["編集アシスタント", "Alexa+ 体験 · シミュレーション", "変更を伝えて確認し、同じタイムラインで制作を続けます。", "ローカルコマンド", "AI プラン", "何を変更しますか？", "変更を確認", "素材はブラウザー内に保持されます。AI プランでは会話とクリップ情報を設定済みモデルへ送信します。", "変更案を確認パネルで適用してください。", "適用しました。プレビュー、追加編集、上部からの書き出しができます。", "コマンド：9:16 · trim first 3s · music 20% · last first。トリムは通常の1倍速動画、音楽は既存クリップ、並べ替えは2クリップが必要です。", "AI プランを利用できません。接続とアクセスコードを確認するか、ローカルコマンドを選んでください。", "アクセスコード（必要な場合）", "AI プランのため会話とクリップ情報を送信"],
  ko: ["편집 도우미", "Alexa+ 경험 · 시뮬레이션", "변경을 요청하고 검토한 다음 같은 타임라인에서 계속 편집하세요.", "로컬 명령", "AI 계획", "무엇을 변경할까요?", "변경 검토", "미디어는 브라우저에 유지됩니다. AI 계획은 대화와 클립 정보를 설정된 모델 서비스로 전송합니다.", "검토 패널에서 변경안을 적용하세요.", "적용되었습니다. 미리보기, 추가 편집 또는 상단에서 내보내기가 가능합니다.", "명령: 9:16 · trim first 3s · music 20% · last first. 자르기는 일반 1배속 동영상, 음악은 기존 클립, 순서 변경은 두 클립이 필요합니다.", "AI 계획을 사용할 수 없습니다. 연결과 접근 코드를 확인하거나 로컬 명령을 선택하세요.", "접근 코드(필요한 경우)", "AI 계획을 위해 대화와 클립 정보 전송"],
  es: ["Asistente de edición", "Experiencia Alexa+ · simulación", "Describe un cambio, revísalo y sigue creando en la misma línea de tiempo.", "Comandos locales", "Planificación IA", "¿Qué quieres cambiar?", "Revisar cambio", "Los medios permanecen en el navegador. La IA envía la conversación y los metadatos al servicio configurado.", "Aplica el cambio en el panel de revisión.", "Cambio aplicado. Puedes previsualizar, seguir editando o exportar desde la barra superior.", "Comandos: 9:16 · trim first 3s · music 20% · last first. El recorte requiere vídeo simple a 1×; la música, un clip existente; el orden, dos clips.", "IA no disponible. Revisa la conexión y el código, o usa comandos locales.", "Código de acceso (si se requiere)", "Enviar conversación y metadatos para planificación IA"],
  fr: ["Assistant de montage", "Expérience Alexa+ · simulation", "Décrivez une modification, vérifiez-la et continuez sur la même timeline.", "Commandes locales", "Planification IA", "Que souhaitez-vous modifier ?", "Vérifier", "Les médias restent dans le navigateur. L’IA transmet la conversation et les métadonnées au service configuré.", "Appliquez la modification dans le panneau de vérification.", "Modification appliquée. Prévisualisez, continuez le montage ou exportez depuis la barre supérieure.", "Commandes : 9:16 · trim first 3s · music 20% · last first. Le découpage nécessite une vidéo simple à 1× ; la musique, un clip existant ; l’ordre, deux clips.", "IA indisponible. Vérifiez la connexion et le code ou utilisez les commandes locales.", "Code d’accès (si nécessaire)", "Envoyer conversation et métadonnées pour la planification IA"],
  de: ["Schnittassistent", "Alexa+ Erlebnis · Simulation", "Beschreibe eine Änderung, prüfe sie und arbeite auf derselben Timeline weiter.", "Lokale Befehle", "KI-Planung", "Was möchtest du ändern?", "Änderung prüfen", "Medien bleiben im Browser. Die KI sendet Gespräch und Clip-Metadaten an den konfigurierten Dienst.", "Übernimm den Vorschlag im Prüfbereich.", "Übernommen. Vorschau, weitere Bearbeitung oder Export über die obere Leiste sind möglich.", "Befehle: 9:16 · trim first 3s · music 20% · last first. Kürzen braucht einfaches 1×-Video; Musik einen vorhandenen Clip; Sortieren zwei Clips.", "KI nicht verfügbar. Verbindung und Zugangscode prüfen oder lokale Befehle nutzen.", "Zugangscode (falls erforderlich)", "Gespräch und Metadaten zur KI-Planung senden"],
  pt: ["Assistente de edição", "Experiência Alexa+ · simulação", "Descreva uma alteração, revise e continue na mesma linha do tempo.", "Comandos locais", "Planejamento IA", "O que deseja alterar?", "Revisar alteração", "A mídia permanece no navegador. A IA envia a conversa e os metadados ao serviço configurado.", "Aplique a alteração no painel de revisão.", "Alteração aplicada. Visualize, continue editando ou exporte pela barra superior.", "Comandos: 9:16 · trim first 3s · music 20% · last first. Corte exige vídeo simples em 1×; música, um clipe existente; ordem, dois clipes.", "IA indisponível. Verifique conexão e código ou use comandos locais.", "Código de acesso (se necessário)", "Enviar conversa e metadados para planejamento IA"],
  th: ["ผู้ช่วยตัดต่อ", "ประสบการณ์ Alexa+ · จำลอง", "บอกสิ่งที่ต้องการแก้ไข ตรวจสอบ แล้วทำงานต่อบนไทม์ไลน์เดิม", "คำสั่งในเครื่อง", "วางแผนด้วย AI", "ต้องการแก้ไขอะไร?", "ตรวจสอบการแก้ไข", "สื่ออยู่ในเบราว์เซอร์ การวางแผน AI ส่งบทสนทนาและข้อมูลคลิปไปยังบริการที่ตั้งค่าไว้", "ใช้การแก้ไขในแผงตรวจสอบ", "แก้ไขแล้ว ดูตัวอย่าง แก้ไขต่อ หรือส่งออกจากแถบด้านบนได้", "คำสั่ง: 9:16 · trim first 3s · music 20% · last first การตัดต้องใช้วิดีโอปกติ 1× เพลงต้องมีคลิปเพลง และการเรียงต้องมีสองคลิป", "AI ไม่พร้อมใช้งาน ตรวจสอบการเชื่อมต่อและรหัส หรือใช้คำสั่งในเครื่อง", "รหัสเข้าใช้งาน (หากจำเป็น)", "ส่งบทสนทนาและข้อมูลคลิปเพื่อวางแผน AI"],
  vi: ["Trợ lý dựng phim", "Trải nghiệm Alexa+ · mô phỏng", "Mô tả thay đổi, xem xét rồi tiếp tục trên cùng dòng thời gian.", "Lệnh cục bộ", "Lập kế hoạch AI", "Bạn muốn thay đổi gì?", "Xem xét thay đổi", "Nội dung đa phương tiện ở trong trình duyệt. AI gửi hội thoại và thông tin clip đến dịch vụ đã cấu hình.", "Áp dụng thay đổi trong bảng xem xét.", "Đã áp dụng. Xem trước, chỉnh sửa tiếp hoặc xuất từ thanh trên cùng.", "Lệnh: 9:16 · trim first 3s · music 20% · last first. Cắt cần video đơn giản 1×; nhạc cần clip có sẵn; sắp xếp cần hai clip.", "AI chưa sẵn sàng. Kiểm tra kết nối và mã hoặc dùng lệnh cục bộ.", "Mã truy cập (nếu cần)", "Gửi hội thoại và thông tin clip để lập kế hoạch AI"],
  ru: ["Помощник монтажа", "Опыт Alexa+ · симуляция", "Опишите изменение, проверьте его и продолжите на той же шкале времени.", "Локальные команды", "Планирование ИИ", "Что изменить?", "Проверить изменение", "Медиа остаются в браузере. ИИ отправляет диалог и метаданные настроенному сервису.", "Примените изменение в панели проверки.", "Применено. Можно просмотреть, продолжить монтаж или экспортировать через верхнюю панель.", "Команды: 9:16 · trim first 3s · music 20% · last first. Обрезка требует простого видео 1×; музыка — готового клипа; порядок — двух клипов.", "ИИ недоступен. Проверьте соединение и код или используйте локальные команды.", "Код доступа (при необходимости)", "Отправить диалог и метаданные для планирования ИИ"],
  it: ["Assistente di montaggio", "Esperienza Alexa+ · simulazione", "Descrivi una modifica, verificala e continua sulla stessa timeline.", "Comandi locali", "Pianificazione IA", "Cosa vuoi modificare?", "Verifica modifica", "I media restano nel browser. L’IA invia conversazione e metadati al servizio configurato.", "Applica la modifica nel pannello di verifica.", "Modifica applicata. Puoi visualizzare, continuare o esportare dalla barra superiore.", "Comandi: 9:16 · trim first 3s · music 20% · last first. Il taglio richiede video semplice a 1×; la musica un clip esistente; l’ordine due clip.", "IA non disponibile. Controlla connessione e codice o usa i comandi locali.", "Codice di accesso (se richiesto)", "Invia conversazione e metadati per la pianificazione IA"],
  id: ["Asisten penyuntingan", "Pengalaman Alexa+ · simulasi", "Jelaskan perubahan, tinjau, lalu lanjutkan di linimasa yang sama.", "Perintah lokal", "Perencanaan AI", "Apa yang ingin diubah?", "Tinjau perubahan", "Media tetap di browser. AI mengirim percakapan dan metadata klip ke layanan yang dikonfigurasi.", "Terapkan perubahan di panel tinjauan.", "Sudah diterapkan. Pratinjau, lanjutkan menyunting, atau ekspor dari bilah atas.", "Perintah: 9:16 · trim first 3s · music 20% · last first. Pemangkasan perlu video sederhana 1×; musik perlu klip yang ada; pengurutan perlu dua klip.", "AI tidak tersedia. Periksa koneksi dan kode atau gunakan perintah lokal.", "Kode akses (jika diperlukan)", "Kirim percakapan dan metadata untuk perencanaan AI"],
};
export function competitionCopy(language) {
  const row = rows[String(language || "en").split(/[-_]/)[0]] || rows.en;
  return Object.fromEntries(keys.map((key, index) => [key, row[index]]));
}
