const keys = ["title", "hint", "saved", "restore", "new", "kept", "download", "prepare", "cancel", "retry", "error", "conflict", "checking"];
const rows = {
  zh: ["继续上次的创作？", "发现已保存的工程，恢复后可继续编辑。", "上次保存", "恢复工程", "开始新工程", "旧工程会保留在工程列表中。", "正在下载工程素材", "正在准备时间线", "取消恢复", "重试恢复", "恢复未完成，旧工程仍然保留。", "检测到新的编辑，当前内容未被覆盖。", "正在读取工程信息"],
  en: ["Continue where you left off?", "A saved project is ready to restore and edit.", "Last saved", "Restore project", "Start a new project", "Your previous project stays in My projects.", "Downloading project media", "Preparing the timeline", "Cancel recovery", "Retry recovery", "Recovery did not finish. Your saved project is kept.", "New edits were detected. Your current work was not overwritten.", "Reading project information"],
  ja: ["前回の続きを編集しますか？", "保存済みのプロジェクトを復元して編集できます。", "最終保存", "プロジェクトを復元", "新しいプロジェクト", "前のプロジェクトは一覧に残ります。", "素材をダウンロード中", "タイムラインを準備中", "復元をキャンセル", "復元を再試行", "復元できませんでした。保存済みの工程は保持されています。", "新しい編集を検出しました。現在の作業は上書きしていません。", "プロジェクト情報を読み込み中"],
  ko: ["이전 작업을 이어서 할까요?", "저장된 프로젝트를 복원하여 편집할 수 있습니다.", "마지막 저장", "프로젝트 복원", "새 프로젝트 시작", "이전 프로젝트는 목록에 보관됩니다.", "프로젝트 미디어 다운로드 중", "타임라인 준비 중", "복원 취소", "복원 재시도", "복원을 완료하지 못했습니다. 저장된 프로젝트는 유지됩니다.", "새 편집이 감지되었습니다. 현재 작업을 덮어쓰지 않았습니다.", "프로젝트 정보 읽는 중"],
  es: ["¿Continuar donde lo dejaste?", "Puedes restaurar tu proyecto guardado y seguir editando.", "Último guardado", "Restaurar proyecto", "Crear proyecto nuevo", "Tu proyecto anterior se conserva en la lista.", "Descargando archivos del proyecto", "Preparando la línea de tiempo", "Cancelar restauración", "Reintentar restauración", "No se completó la restauración. Tu proyecto sigue guardado.", "Se detectaron nuevas ediciones. Tu trabajo actual no se sobrescribió.", "Leyendo información del proyecto"],
  fr: ["Reprendre votre création ?", "Restaurez votre projet enregistré pour continuer à le modifier.", "Dernier enregistrement", "Restaurer le projet", "Créer un nouveau projet", "Votre ancien projet reste dans la liste.", "Téléchargement des médias", "Préparation de la timeline", "Annuler la restauration", "Réessayer", "La restauration n’a pas abouti. Votre projet reste enregistré.", "De nouvelles modifications ont été détectées. Votre travail n’a pas été écrasé.", "Lecture des informations du projet"],
  de: ["Letzte Arbeit fortsetzen?", "Stelle dein gespeichertes Projekt wieder her und bearbeite es weiter.", "Zuletzt gespeichert", "Projekt wiederherstellen", "Neues Projekt starten", "Dein bisheriges Projekt bleibt in der Liste.", "Projektmedien werden geladen", "Zeitleiste wird vorbereitet", "Wiederherstellung abbrechen", "Erneut versuchen", "Die Wiederherstellung wurde nicht abgeschlossen. Dein Projekt bleibt gespeichert.", "Neue Änderungen erkannt. Deine aktuelle Arbeit wurde nicht überschrieben.", "Projektinformationen werden gelesen"],
  pt: ["Continuar de onde parou?", "Restaure seu projeto salvo para continuar editando.", "Último salvamento", "Restaurar projeto", "Iniciar novo projeto", "Seu projeto anterior permanece na lista.", "Baixando mídias do projeto", "Preparando a linha do tempo", "Cancelar restauração", "Tentar novamente", "A restauração não terminou. Seu projeto continua salvo.", "Novas edições foram detectadas. Seu trabalho atual não foi substituído.", "Lendo informações do projeto"],
  th: ["ทำงานต่อจากครั้งที่แล้วไหม?", "กู้คืนโปรเจกต์ที่บันทึกไว้เพื่อแก้ไขต่อได้", "บันทึกล่าสุด", "กู้คืนโปรเจกต์", "เริ่มโปรเจกต์ใหม่", "โปรเจกต์เดิมจะยังอยู่ในรายการ", "กำลังดาวน์โหลดสื่อของโปรเจกต์", "กำลังเตรียมไทม์ไลน์", "ยกเลิกการกู้คืน", "ลองกู้คืนอีกครั้ง", "กู้คืนไม่สำเร็จ โปรเจกต์ที่บันทึกไว้ยังคงอยู่", "ตรวจพบการแก้ไขใหม่ งานปัจจุบันไม่ได้ถูกเขียนทับ", "กำลังอ่านข้อมูลโปรเจกต์"],
  vi: ["Tiếp tục công việc trước đó?", "Khôi phục dự án đã lưu để tiếp tục chỉnh sửa.", "Lưu lần cuối", "Khôi phục dự án", "Bắt đầu dự án mới", "Dự án cũ vẫn được giữ trong danh sách.", "Đang tải tư liệu dự án", "Đang chuẩn bị dòng thời gian", "Hủy khôi phục", "Thử khôi phục lại", "Khôi phục chưa hoàn tất. Dự án đã lưu vẫn được giữ.", "Phát hiện chỉnh sửa mới. Công việc hiện tại không bị ghi đè.", "Đang đọc thông tin dự án"],
  ru: ["Продолжить прежнюю работу?", "Восстановите сохранённый проект и продолжите редактирование.", "Последнее сохранение", "Восстановить проект", "Начать новый проект", "Прежний проект останется в списке.", "Загрузка медиа проекта", "Подготовка таймлайна", "Отменить восстановление", "Повторить восстановление", "Восстановление не завершено. Сохранённый проект не удалён.", "Обнаружены новые правки. Текущая работа не перезаписана.", "Чтение информации о проекте"],
  it: ["Riprendere il lavoro precedente?", "Ripristina il progetto salvato per continuare a modificarlo.", "Ultimo salvataggio", "Ripristina progetto", "Inizia un nuovo progetto", "Il progetto precedente resta nell’elenco.", "Download dei file del progetto", "Preparazione della timeline", "Annulla ripristino", "Riprova", "Il ripristino non è terminato. Il progetto salvato è conservato.", "Rilevate nuove modifiche. Il lavoro attuale non è stato sovrascritto.", "Lettura delle informazioni del progetto"],
  id: ["Lanjutkan pekerjaan sebelumnya?", "Pulihkan proyek tersimpan untuk melanjutkan pengeditan.", "Terakhir disimpan", "Pulihkan proyek", "Mulai proyek baru", "Proyek sebelumnya tetap ada di daftar.", "Mengunduh media proyek", "Menyiapkan linimasa", "Batalkan pemulihan", "Coba pulihkan lagi", "Pemulihan belum selesai. Proyek tersimpan tetap aman.", "Perubahan baru terdeteksi. Pekerjaan saat ini tidak ditimpa.", "Membaca informasi proyek"],
};
export const getAnnaRecoveryCopy = language => Object.fromEntries(keys.map((key, index) => [key, (rows[language] || rows.en)[index]]));
