const rows = {
  zh: ['等待云端备份','云端备份中','云端备份完成','云端备份失败，本地保存仍保留','云端有其他修改，本地工程已保留，未覆盖云端','重试备份','新建或切换前先保存到此浏览器，云端备份在后台完成。'],
  en: ['Cloud backup pending','Backing up to cloud','Cloud backup complete','Cloud backup failed; local save retained','Cloud changed elsewhere; local project retained, cloud not overwritten','Retry backup','Projects are saved in this browser before creating or switching. Cloud backup runs in the background.'],
  ja: ['クラウドバックアップ待機中','クラウドにバックアップ中','クラウドバックアップ完了','クラウドバックアップ失敗。ローカル保存は保持されています','別の場所でクラウドが変更されました。ローカルを保持し、クラウドは上書きしていません','バックアップを再試行','新規作成や切り替え前にこのブラウザーに保存します。クラウドバックアップはバックグラウンドで行います。'],
  ko: ['클라우드 백업 대기 중','클라우드 백업 중','클라우드 백업 완료','클라우드 백업 실패. 로컬 저장은 유지됩니다','다른 곳에서 클라우드가 변경되었습니다. 로컬 프로젝트를 유지하며 클라우드를 덮어쓰지 않았습니다','백업 재시도','생성 또는 전환 전에 이 브라우저에 저장합니다. 클라우드 백업은 백그라운드에서 진행됩니다.'],
  es: ['Copia en la nube pendiente','Creando copia en la nube','Copia en la nube completa','Falló la copia en la nube; se conserva el guardado local','La nube cambió en otro lugar; se conserva el proyecto local sin sobrescribir la nube','Reintentar copia','Antes de crear o cambiar de proyecto, se guarda en este navegador. La copia en la nube se realiza en segundo plano.'],
  fr: ['Sauvegarde cloud en attente','Sauvegarde cloud en cours','Sauvegarde cloud terminée','Échec du cloud ; sauvegarde locale conservée','Le cloud a changé ailleurs ; projet local conservé, cloud non écrasé','Réessayer la sauvegarde','Les projets sont enregistrés dans ce navigateur avant leur création ou changement. La sauvegarde cloud se fait en arrière-plan.'],
  de: ['Cloud-Sicherung ausstehend','Cloud-Sicherung läuft','Cloud-Sicherung abgeschlossen','Cloud-Sicherung fehlgeschlagen; lokale Kopie bleibt erhalten','Cloud wurde andernorts geändert; lokales Projekt bleibt erhalten, Cloud nicht überschrieben','Sicherung wiederholen','Vor dem Erstellen oder Wechseln wird in diesem Browser gespeichert. Die Cloud-Sicherung läuft im Hintergrund.'],
  pt: ['Backup na nuvem pendente','Fazendo backup na nuvem','Backup na nuvem concluído','Falha no backup; cópia local preservada','A nuvem mudou em outro local; projeto local preservado, nuvem não sobrescrita','Tentar backup novamente','Os projetos são salvos neste navegador antes de criar ou trocar. O backup na nuvem ocorre em segundo plano.'],
  th: ['รอสำรองข้อมูลบนคลาวด์','กำลังสำรองข้อมูลบนคลาวด์','สำรองข้อมูลบนคลาวด์แล้ว','สำรองบนคลาวด์ไม่สำเร็จ แต่ยังเก็บข้อมูลในเครื่องไว้','ข้อมูลคลาวด์เปลี่ยนจากที่อื่น เก็บโปรเจกต์ในเครื่องไว้และไม่เขียนทับคลาวด์','ลองสำรองอีกครั้ง','บันทึกโปรเจกต์ในเบราว์เซอร์นี้ก่อนสร้างหรือสลับ การสำรองบนคลาวด์ทำงานเบื้องหลัง'],
  vi: ['Đang chờ sao lưu đám mây','Đang sao lưu đám mây','Đã sao lưu đám mây','Sao lưu đám mây thất bại; bản lưu cục bộ vẫn còn','Đám mây đã thay đổi ở nơi khác; giữ dự án cục bộ, không ghi đè đám mây','Thử sao lưu lại','Lưu dự án trong trình duyệt này trước khi tạo hoặc chuyển. Sao lưu đám mây chạy trong nền.'],
  ru: ['Ожидание облачной копии','Копирование в облако','Облачная копия готова','Сбой облачной копии; локальное сохранение осталось','Облако изменено в другом месте; локальный проект сохранён, облако не перезаписано','Повторить копирование','Перед созданием или переключением проект сохраняется в этом браузере. Облачная копия создаётся в фоне.'],
  it: ['Backup cloud in attesa','Backup cloud in corso','Backup cloud completato','Backup cloud non riuscito; salvataggio locale conservato','Il cloud è cambiato altrove; progetto locale conservato, cloud non sovrascritto','Riprova backup','I progetti vengono salvati in questo browser prima di crearli o cambiarli. Il backup cloud avviene in background.'],
  id: ['Cadangan cloud tertunda','Mencadangkan ke cloud','Cadangan cloud selesai','Cadangan cloud gagal; simpanan lokal tetap ada','Cloud diubah di tempat lain; proyek lokal tetap ada, cloud tidak ditimpa','Coba cadangkan lagi','Proyek disimpan di browser ini sebelum membuat atau beralih. Pencadangan cloud berjalan di latar belakang.'],
};
export function getAnnaBackupCopy(language) {
  return Object.fromEntries(['pending','syncing','saved','error','conflict','retry','hint'].map((key, index) => [key, (rows[language] || rows.en)[index]]));
}
