const keys=['title','brush','region','size','undo','clear','prompt','apply','download','original','result','hint','error'];
const rows={
zh:['局部编辑图片','笔刷','区域标注','笔刷大小','撤销标注','清空标注','描述选中区域如何修改','生成修改','下载图片','原图','修改结果','涂抹或框选需要修改的区域。未选中的区域保持原样；需要支持蒙版的编辑模型。','编辑失败，请检查编辑权限、额度及模型是否支持蒙版，然后重试。'],
en:['Edit image area','Brush','Select area','Brush size','Undo mark','Clear marks','Describe changes to the selected area','Generate edit','Download image','Original','Edited result','Paint or select an area. Unselected areas stay unchanged; a mask-capable editing model is required.','Editing failed. Check permissions, quota and mask support, then retry.'],
ja:['画像の部分編集','ブラシ','範囲選択','ブラシサイズ','注釈を元に戻す','注釈を消去','選択範囲の変更を説明','編集を生成','画像を保存','元画像','編集結果','編集する範囲を塗るか選択します。範囲外は保持されます。マスク対応モデルが必要です。','編集に失敗しました。権限、利用枠、マスク対応を確認してください。'],
ko:['이미지 부분 편집','브러시','영역 선택','브러시 크기','표시 취소','표시 지우기','선택 영역의 변경 내용','편집 생성','이미지 다운로드','원본','편집 결과','수정할 영역을 칠하거나 선택하세요. 다른 영역은 유지됩니다. 마스크 지원 모델이 필요합니다.','편집 실패. 권한, 사용량 및 마스크 지원을 확인하세요.'],
es:['Editar un área','Pincel','Seleccionar área','Tamaño del pincel','Deshacer marca','Borrar marcas','Describe los cambios del área seleccionada','Generar edición','Descargar imagen','Original','Resultado','Pinta o selecciona un área. El resto se conserva; necesitas un modelo compatible con máscaras.','Error de edición. Comprueba permisos, cuota y compatibilidad con máscaras.'],
fr:['Modifier une zone','Pinceau','Sélectionner une zone','Taille du pinceau','Annuler le tracé','Effacer les tracés','Décrivez les modifications de la zone','Générer la modification','Télécharger l’image','Original','Résultat','Peignez ou sélectionnez une zone. Le reste est conservé ; un modèle compatible avec les masques est requis.','Échec de la modification. Vérifiez les droits, le quota et la prise en charge des masques.'],
de:['Bildbereich bearbeiten','Pinsel','Bereich wählen','Pinselgröße','Markierung zurücknehmen','Markierungen löschen','Änderungen im gewählten Bereich beschreiben','Bearbeitung erzeugen','Bild herunterladen','Original','Ergebnis','Bereich malen oder auswählen. Der Rest bleibt erhalten; ein Modell mit Maskenunterstützung ist erforderlich.','Bearbeitung fehlgeschlagen. Berechtigungen, Kontingent und Maskenunterstützung prüfen.'],
pt:['Editar área da imagem','Pincel','Selecionar área','Tamanho do pincel','Desfazer marca','Limpar marcas','Descreva as alterações na área','Gerar edição','Baixar imagem','Original','Resultado','Pinte ou selecione uma área. O restante é preservado; é necessário um modelo com suporte a máscaras.','Falha na edição. Verifique permissões, cota e suporte a máscaras.'],
th:['แก้ไขบางส่วนของภาพ','พู่กัน','เลือกพื้นที่','ขนาดพู่กัน','เลิกทำเครื่องหมาย','ล้างเครื่องหมาย','อธิบายการแก้ไขพื้นที่ที่เลือก','สร้างการแก้ไข','ดาวน์โหลดภาพ','ต้นฉบับ','ผลลัพธ์','ระบายหรือเลือกพื้นที่ที่ต้องการแก้ไข ส่วนอื่นคงเดิม ต้องใช้โมเดลที่รองรับมาสก์','แก้ไขไม่สำเร็จ ตรวจสอบสิทธิ์ โควตา และการรองรับมาสก์'],
vi:['Sửa vùng ảnh','Cọ vẽ','Chọn vùng','Cỡ cọ','Hoàn tác đánh dấu','Xóa đánh dấu','Mô tả thay đổi cho vùng đã chọn','Tạo bản sửa','Tải ảnh xuống','Ảnh gốc','Kết quả','Tô hoặc chọn vùng cần sửa. Phần còn lại giữ nguyên; cần mô hình hỗ trợ mặt nạ.','Sửa thất bại. Kiểm tra quyền, hạn mức và hỗ trợ mặt nạ.'],
ru:['Редактировать область','Кисть','Выбрать область','Размер кисти','Отменить отметку','Удалить отметки','Опишите изменения выбранной области','Создать правку','Скачать изображение','Оригинал','Результат','Закрасьте или выберите область. Остальное сохранится; нужна модель с поддержкой масок.','Ошибка редактирования. Проверьте разрешения, лимит и поддержку масок.'],
it:['Modifica area immagine','Pennello','Seleziona area','Dimensione pennello','Annulla segno','Cancella segni','Descrivi le modifiche all’area selezionata','Genera modifica','Scarica immagine','Originale','Risultato','Dipingi o seleziona un’area. Il resto viene preservato; serve un modello compatibile con le maschere.','Modifica non riuscita. Controlla permessi, quota e supporto delle maschere.'],
id:['Edit area gambar','Kuas','Pilih area','Ukuran kuas','Urungkan tanda','Hapus tanda','Jelaskan perubahan pada area terpilih','Buat edit','Unduh gambar','Asli','Hasil','Warnai atau pilih area. Bagian lain tetap sama; perlu model yang mendukung masker.','Edit gagal. Periksa izin, kuota, dan dukungan masker.']};
export function getImageEditCopy(language){return Object.fromEntries(keys.map((key,i)=>[key,(rows[language]||rows.en)[i]]));}
