import { getAnnaImageCopy } from "./plugins/generation/providers/anna/copy.js";
import { ANIMATION_COPY } from "./i18nAnimation.js";
import { SILENCE_REMOVAL_COPY } from "./i18nSilenceRemoval.js";
const rows = {
  zh: ['处理字幕或去水印','处理已读取片段的自动字幕或视频去水印，返回结果而不修改时间线。','查看处理结果','抽帧检查去水印视频结果。','审阅处理结果','把处理结果生成字幕插入或视频替换方案，不立即应用。','当前环境暂不支持这项处理。','未得到有效结果，请检查素材或识别语言。','处理结果已失效，请重新处理。','请先抽帧检查去水印结果。','本次会话的处理结果已满，请新开会话。','正在处理素材…','自动字幕可能由浏览器识别服务联网处理所选音频；去水印在本机处理。'],
  en: ['Process captions or watermark','Process automatic captions or video watermark removal for an inspected clip without changing the timeline.','Inspect processed video','Sample frames from the repaired video.','Review processing result','Prepare caption insertion or video replacement for review without applying it.','This processing is unavailable in the current environment.','No valid result. Check the media or recognition language.','Processing result expired. Process again.','Inspect repaired video frames first.','Processing results are full. Start a new conversation.','Processing media…','Automatic captions may send selected audio to the browser recognition service; watermark removal runs locally.'],
  ja: ['字幕・透かしを処理','確認済みクリップの自動字幕または動画の透かし除去を処理します。タイムラインは変更しません。','処理動画を確認','修復動画のフレームを抽出します。','処理結果をレビュー','字幕追加または動画置換の案を作成し、適用せず確認します。','現在の環境ではこの処理を利用できません。','有効な結果がありません。素材または認識言語を確認してください。','処理結果が失効しました。再処理してください。','先に修復動画のフレームを確認してください。','処理結果が上限に達しました。新しい会話を開始してください。','素材を処理中…','自動字幕では選択音声をブラウザーの認識サービスへ送信する場合があります。透かし除去はローカルで処理します。'],
  ko: ['자막 또는 워터마크 처리','확인한 클립의 자동 자막이나 영상 워터마크 제거를 처리하며 타임라인은 변경하지 않습니다.','처리 영상 확인','복구 영상의 프레임을 추출합니다.','처리 결과 검토','적용 전에 자막 추가 또는 영상 교체 계획을 만듭니다.','현재 환경에서 이 처리를 사용할 수 없습니다.','유효한 결과가 없습니다. 미디어나 인식 언어를 확인하세요.','결과가 만료되었습니다. 다시 처리하세요.','복구 영상의 프레임을 먼저 확인하세요.','처리 결과가 가득 찼습니다. 새 대화를 시작하세요.','미디어 처리 중…','자동 자막은 선택한 오디오를 브라우저 인식 서비스에 보낼 수 있습니다. 워터마크 제거는 로컬에서 실행됩니다.'],
  es: ['Procesar subtítulos o marca','Procesa subtítulos automáticos o elimina marcas del vídeo inspeccionado sin modificar la línea de tiempo.','Inspeccionar vídeo procesado','Extrae fotogramas del vídeo reparado.','Revisar resultado','Prepara la inserción de subtítulos o sustitución de vídeo sin aplicarla.','Este proceso no está disponible en el entorno actual.','Sin resultado válido. Comprueba el medio o idioma.','El resultado caducó. Procesa de nuevo.','Inspecciona primero el vídeo reparado.','Resultados completos. Inicia otra conversación.','Procesando medios…','Los subtítulos pueden enviar el audio seleccionado al servicio de reconocimiento del navegador; la eliminación de marcas es local.'],
  fr: ['Traiter sous-titres ou filigrane','Génère les sous-titres ou retire le filigrane du clip inspecté sans modifier la timeline.','Inspecter la vidéo traitée','Extrait des images de la vidéo réparée.','Vérifier le résultat','Prépare l’ajout des sous-titres ou le remplacement vidéo sans l’appliquer.','Ce traitement est indisponible dans cet environnement.','Aucun résultat valide. Vérifiez le média ou la langue.','Résultat expiré. Relancez le traitement.','Inspectez d’abord la vidéo réparée.','Limite atteinte. Ouvrez une nouvelle conversation.','Traitement du média…','Les sous-titres peuvent envoyer l’audio choisi au service de reconnaissance du navigateur ; le retrait du filigrane est local.'],
  de: ['Untertitel oder Wasserzeichen bearbeiten','Erstellt Untertitel oder entfernt Wasserzeichen aus dem geprüften Clip, ohne die Timeline zu ändern.','Bearbeitetes Video prüfen','Entnimmt Bilder aus dem reparierten Video.','Ergebnis prüfen','Bereitet Untertitel oder Videoersatz zur Prüfung vor, ohne Änderungen anzuwenden.','Diese Verarbeitung ist hier nicht verfügbar.','Kein gültiges Ergebnis. Medium oder Sprache prüfen.','Ergebnis abgelaufen. Erneut verarbeiten.','Zuerst reparierte Videobilder prüfen.','Ergebnislimit erreicht. Neues Gespräch starten.','Medium wird verarbeitet…','Untertitel können ausgewähltes Audio an den Erkennungsdienst des Browsers senden; Wasserzeichen werden lokal entfernt.'],
  pt: ['Processar legendas ou marca','Gera legendas ou remove marcas do clipe inspecionado sem alterar a linha do tempo.','Inspecionar vídeo processado','Extrai quadros do vídeo reparado.','Revisar resultado','Prepara legendas ou substituição de vídeo sem aplicar alterações.','Este processamento não está disponível neste ambiente.','Sem resultado válido. Verifique a mídia ou o idioma.','Resultado expirado. Processe novamente.','Inspecione primeiro o vídeo reparado.','Limite de resultados atingido. Inicie outra conversa.','Processando mídia…','As legendas podem enviar o áudio escolhido ao serviço de reconhecimento do navegador; a remoção de marcas é local.'],
  th: ['ประมวลผลคำบรรยายหรือลายน้ำ','สร้างคำบรรยายหรือลบลายน้ำของคลิปที่ตรวจสอบ โดยไม่แก้ไขไทม์ไลน์','ตรวจสอบวิดีโอที่ประมวลผล','ดึงเฟรมจากวิดีโอที่ซ่อมแล้ว','ตรวจสอบผลลัพธ์','เตรียมเพิ่มคำบรรยายหรือแทนที่วิดีโอโดยยังไม่ใช้การเปลี่ยนแปลง','สภาพแวดล้อมนี้ยังไม่รองรับการประมวลผลนี้','ไม่มีผลลัพธ์ที่ใช้ได้ ตรวจสอบสื่อหรือภาษา','ผลลัพธ์หมดอายุ กรุณาประมวลผลใหม่','ตรวจสอบเฟรมวิดีโอที่ซ่อมก่อน','ผลลัพธ์เต็มแล้ว กรุณาเริ่มบทสนทนาใหม่','กำลังประมวลผลสื่อ…','คำบรรยายอาจส่งเสียงที่เลือกไปยังบริการรู้จำของเบราว์เซอร์ การลบลายน้ำทำในเครื่อง'],
  vi: ['Xử lý phụ đề hoặc hình mờ','Tạo phụ đề hoặc xóa hình mờ của clip đã kiểm tra mà không sửa dòng thời gian.','Kiểm tra video đã xử lý','Trích khung hình từ video đã sửa.','Xem xét kết quả','Chuẩn bị thêm phụ đề hoặc thay video mà chưa áp dụng.','Môi trường hiện tại chưa hỗ trợ xử lý này.','Không có kết quả hợp lệ. Kiểm tra nội dung hoặc ngôn ngữ.','Kết quả đã hết hạn. Hãy xử lý lại.','Kiểm tra khung hình video đã sửa trước.','Đã đầy kết quả. Bắt đầu cuộc trò chuyện mới.','Đang xử lý nội dung…','Phụ đề có thể gửi âm thanh đã chọn đến dịch vụ nhận dạng của trình duyệt; xóa hình mờ chạy cục bộ.'],
  ru: ['Обработать субтитры или водяной знак','Создаёт субтитры или удаляет водяной знак проверенного клипа без изменения шкалы времени.','Проверить обработанное видео','Извлекает кадры исправленного видео.','Проверить результат','Готовит добавление субтитров или замену видео без применения изменений.','Эта обработка недоступна в текущей среде.','Нет корректного результата. Проверьте материал или язык.','Результат устарел. Повторите обработку.','Сначала проверьте кадры исправленного видео.','Достигнут предел результатов. Начните новый разговор.','Обработка материала…','Для субтитров выбранное аудио может передаваться службе распознавания браузера; удаление водяного знака выполняется локально.'],
  it: ['Elabora sottotitoli o filigrana','Genera sottotitoli o rimuove la filigrana dalla clip verificata senza modificare la timeline.','Esamina video elaborato','Estrae fotogrammi dal video riparato.','Rivedi risultato','Prepara sottotitoli o sostituzione video senza applicare modifiche.','Questa elaborazione non è disponibile nell’ambiente attuale.','Nessun risultato valido. Controlla il contenuto o la lingua.','Risultato scaduto. Elabora nuovamente.','Esamina prima i fotogrammi del video riparato.','Limite risultati raggiunto. Apri una nuova conversazione.','Elaborazione contenuti…','I sottotitoli possono inviare l’audio scelto al servizio di riconoscimento del browser; la rimozione della filigrana è locale.'],
  id: ['Proses subtitel atau tanda air','Membuat subtitel atau menghapus tanda air klip yang diperiksa tanpa mengubah linimasa.','Periksa video hasil','Mengambil bingkai dari video yang diperbaiki.','Tinjau hasil','Menyiapkan subtitel atau penggantian video tanpa menerapkannya.','Pemrosesan ini tidak tersedia di lingkungan saat ini.','Tidak ada hasil valid. Periksa media atau bahasa.','Hasil kedaluwarsa. Proses ulang.','Periksa bingkai video hasil terlebih dahulu.','Batas hasil tercapai. Mulai percakapan baru.','Memproses media…','Subtitel dapat mengirim audio pilihan ke layanan pengenalan browser; penghapusan tanda air berjalan lokal.'],
};
const keys = ['toolAiProcessTitle','toolAiProcessDescription','toolAiFramesTitle','toolAiFramesDescription','toolAiPreviewTitle','toolAiPreviewDescription','aiUnavailable','aiEmpty','aiExpired','aiInspectRequired','aiLimit','processing','aiPrivacy'];
export const WEB_MCP_AI_COPY = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, index) => [key, values[index]]))]));
for (const [locale, copy] of Object.entries(WEB_MCP_AI_COPY)) Object.assign(copy, ANIMATION_COPY[locale]);

for (const [locale, copy] of Object.entries(WEB_MCP_AI_COPY)) {
  const pause = SILENCE_REMOVAL_COPY[locale];
  copy.aiNoPauses = pause.pauseEmpty;
  copy.toolAiProcessTitle += ` · ${pause.pauseTitle}`;
  copy.toolAiProcessDescription += ` ${pause.pauseIntro}`;
  copy.toolAiPreviewDescription += ` ${pause.pauseApply}`;
}

const NARRATION_LENGTH_COPY = {"zh": "解说超出指定时段，请精简文案后重试。", "en": "Narration exceeds its time slot. Shorten the text and retry.", "ja": "ナレーションが指定時間を超えています。文章を短くして再試行してください。", "ko": "해설이 지정 시간을 초과했습니다. 문장을 줄여 다시 시도하세요.", "es": "La narración supera el intervalo. Acorta el texto y reintenta.", "fr": "La narration dépasse le créneau. Raccourcissez le texte et réessayez.", "de": "Die Erzählung überschreitet das Zeitfenster. Text kürzen und erneut versuchen.", "pt": "A narração excede o intervalo. Encurte o texto e tente novamente.", "th": "เสียงบรรยายยาวเกินช่วงเวลา กรุณาย่อข้อความแล้วลองอีกครั้ง", "vi": "Lời thuyết minh vượt thời lượng. Rút ngắn văn bản rồi thử lại.", "ru": "Озвучка превышает интервал. Сократите текст и повторите.", "it": "La narrazione supera il tempo previsto. Accorcia il testo e riprova.", "id": "Narasi melebihi waktu yang ditentukan. Persingkat teks dan coba lagi."};
for (const [language, text] of Object.entries(NARRATION_LENGTH_COPY)) WEB_MCP_AI_COPY[language].aiNarrationTooLong = text;

for (const [locale, copy] of Object.entries(WEB_MCP_AI_COPY)) { const image = getAnnaImageCopy(locale); copy.toolImageGenerateTitle = image.title; copy.toolImageGenerateDescription = `${image.prompt}. ${image.quota}`; }
