const keys = ["toolAnimationGenerateTitle", "toolAnimationGenerateDescription", "animationUnavailable", "animationFailed"];
const rows = {
  zh: ["生成动画", "在浏览器中生成表格、柱状图、文字动效或信息卡片视频，保存为素材，不修改轨道。", "当前浏览器不支持动画视频编码，请使用支持 WebCodecs 的浏览器。", "动画渲染失败，请减少内容或缩短时长后重试。"],
  en: ["Generate animation", "Render a table, bar chart, animated text or information cards locally into a video asset without changing the timeline.", "This browser cannot encode animation video. Use a browser with WebCodecs support.", "Animation rendering failed. Reduce the content or duration and retry."],
  ja: ["アニメーションを生成", "表、棒グラフ、文字アニメーション、情報カードをブラウザー内で動画素材に変換します。タイムラインは変更しません。", "このブラウザーは動画のエンコードに対応していません。WebCodecs 対応ブラウザーを使用してください。", "描画に失敗しました。内容や時間を減らして再試行してください。"],
  ko: ["애니메이션 생성", "표, 막대그래프, 텍스트 애니메이션 또는 정보 카드를 브라우저에서 영상 소재로 렌더링합니다. 타임라인은 변경하지 않습니다.", "이 브라우저는 애니메이션 영상 인코딩을 지원하지 않습니다. WebCodecs 지원 브라우저를 사용하세요.", "애니메이션 렌더링에 실패했습니다. 내용이나 길이를 줄이고 다시 시도하세요."],
  es: ["Generar animación", "Renderiza tablas, gráficos de barras, texto animado o tarjetas en un video local sin modificar la línea de tiempo.", "Este navegador no puede codificar animaciones. Usa uno compatible con WebCodecs.", "No se pudo renderizar la animación. Reduce el contenido o la duración e inténtalo de nuevo."],
  fr: ["Créer une animation", "Transforme tableaux, graphiques à barres, textes animés ou fiches en vidéo locale sans modifier la timeline.", "Ce navigateur ne peut pas encoder l’animation. Utilisez un navigateur compatible avec WebCodecs.", "Le rendu a échoué. Réduisez le contenu ou la durée et réessayez."],
  de: ["Animation erstellen", "Rendert Tabellen, Balkendiagramme, animierten Text oder Infokarten lokal als Video, ohne die Zeitleiste zu ändern.", "Dieser Browser kann das Animationsvideo nicht kodieren. Verwenden Sie einen Browser mit WebCodecs.", "Das Rendern ist fehlgeschlagen. Inhalt oder Dauer reduzieren und erneut versuchen."],
  pt: ["Gerar animação", "Renderiza tabelas, gráficos de barras, texto animado ou cartões em um vídeo local sem alterar a linha do tempo.", "Este navegador não pode codificar animações. Use um navegador com WebCodecs.", "Falha ao renderizar. Reduza o conteúdo ou a duração e tente novamente."],
  th: ["สร้างแอนิเมชัน", "สร้างวิดีโอตาราง กราฟแท่ง ข้อความเคลื่อนไหว หรือบัตรข้อมูลในเบราว์เซอร์ โดยไม่เปลี่ยนไทม์ไลน์", "เบราว์เซอร์นี้เข้ารหัสวิดีโอแอนิเมชันไม่ได้ กรุณาใช้เบราว์เซอร์ที่รองรับ WebCodecs", "เรนเดอร์ไม่สำเร็จ กรุณาลดเนื้อหาหรือระยะเวลาแล้วลองอีกครั้ง"],
  vi: ["Tạo hoạt ảnh", "Kết xuất bảng, biểu đồ cột, chữ động hoặc thẻ thông tin thành video cục bộ mà không đổi dòng thời gian.", "Trình duyệt này không mã hóa được video hoạt ảnh. Hãy dùng trình duyệt hỗ trợ WebCodecs.", "Kết xuất thất bại. Giảm nội dung hoặc thời lượng rồi thử lại."],
  ru: ["Создать анимацию", "Создаёт локальное видео с таблицей, столбчатой диаграммой, анимированным текстом или карточками, не меняя шкалу времени.", "Браузер не может кодировать анимацию. Используйте браузер с поддержкой WebCodecs.", "Рендеринг не удался. Уменьшите объём содержимого или длительность и повторите."],
  it: ["Genera animazione", "Crea un video locale con tabelle, grafici a barre, testo animato o schede senza modificare la timeline.", "Il browser non può codificare l’animazione. Usa un browser con WebCodecs.", "Rendering non riuscito. Riduci il contenuto o la durata e riprova."],
  id: ["Buat animasi", "Merender tabel, grafik batang, teks animasi atau kartu informasi menjadi video lokal tanpa mengubah linimasa.", "Browser ini tidak dapat mengodekan video animasi. Gunakan browser yang mendukung WebCodecs.", "Render gagal. Kurangi konten atau durasi lalu coba lagi."],
};
export const ANIMATION_COPY = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, index) => [key, values[index]]))]));
