const keys = ['title', 'new', 'name', 'create', 'open', 'rename', 'save', 'cancel', 'current', 'untitled', 'empty', 'loading', 'error', 'hint', 'previous', 'restoreHint', 'refresh'];
const rows = {
  zh: ['我的项目','新建项目','项目名称','保存并新建','打开','重命名','保存名称','取消','当前项目','未命名项目','还没有已保存的项目','正在处理…','操作未完成，请检查保存状态后重试。当前内容仍保留在编辑器中。','新建或切换前会先保存当前工程。请等待云端保存完成。','恢复上一份保存','恢复前会保存当前工程。上一份保存不代表完整的编辑历史。','刷新'],
  en: ['My projects','New project','Project name','Save and create','Open','Rename','Save name','Cancel','Current project','Untitled project','No saved projects yet','Working…','Could not finish. Check the save status and retry. Your current content remains in the editor.','Your current project is saved before creating or switching projects. Wait for cloud saving to finish.','Restore previous save','Your current project is saved before recovery. The previous save is not a full edit history.','Refresh'],
  ja: ['マイプロジェクト','新規プロジェクト','プロジェクト名','保存して新規作成','開く','名前を変更','名前を保存','キャンセル','現在のプロジェクト','無題のプロジェクト','保存済みプロジェクトはありません','処理中…','完了できませんでした。保存状態を確認して再試行してください。現在の内容はエディターに残っています。','新規作成や切り替えの前に現在のプロジェクトを保存します。クラウド保存の完了をお待ちください。','前回の保存を復元','復元前に現在のプロジェクトを保存します。前回の保存は完全な編集履歴ではありません。','更新'],
  ko: ['내 프로젝트','새 프로젝트','프로젝트 이름','저장 후 만들기','열기','이름 변경','이름 저장','취소','현재 프로젝트','제목 없는 프로젝트','저장된 프로젝트가 없습니다','처리 중…','완료하지 못했습니다. 저장 상태를 확인하고 다시 시도하세요. 현재 내용은 편집기에 남아 있습니다.','새로 만들거나 전환하기 전에 현재 프로젝트를 저장합니다. 클라우드 저장 완료를 기다려 주세요.','이전 저장 복원','복원 전에 현재 프로젝트를 저장합니다. 이전 저장은 전체 편집 기록이 아닙니다.','새로고침'],
  es: ['Mis proyectos','Nuevo proyecto','Nombre del proyecto','Guardar y crear','Abrir','Renombrar','Guardar nombre','Cancelar','Proyecto actual','Proyecto sin título','Aún no hay proyectos guardados','Procesando…','No se pudo completar. Revisa el estado de guardado y reintenta. El contenido actual sigue en el editor.','El proyecto actual se guarda antes de crear o cambiar de proyecto. Espera a que termine el guardado en la nube.','Restaurar guardado anterior','El proyecto actual se guarda antes de restaurar. El guardado anterior no es un historial completo.','Actualizar'],
  fr: ['Mes projets','Nouveau projet','Nom du projet','Enregistrer et créer','Ouvrir','Renommer','Enregistrer le nom','Annuler','Projet actuel','Projet sans titre','Aucun projet enregistré','Traitement…','Impossible de terminer. Vérifiez la sauvegarde et réessayez. Le contenu actuel reste dans l’éditeur.','Le projet actuel est enregistré avant la création ou le changement de projet. Attendez la fin de la sauvegarde cloud.','Restaurer la sauvegarde précédente','Le projet actuel est enregistré avant la restauration. La sauvegarde précédente ne constitue pas un historique complet.','Actualiser'],
  de: ['Meine Projekte','Neues Projekt','Projektname','Speichern und erstellen','Öffnen','Umbenennen','Namen speichern','Abbrechen','Aktuelles Projekt','Unbenanntes Projekt','Noch keine gespeicherten Projekte','Wird bearbeitet…','Vorgang nicht abgeschlossen. Speicherstatus prüfen und erneut versuchen. Der aktuelle Inhalt bleibt im Editor.','Vor dem Erstellen oder Wechseln wird das aktuelle Projekt gespeichert. Bitte auf den Cloud-Speichervorgang warten.','Vorherigen Stand wiederherstellen','Vor der Wiederherstellung wird das aktuelle Projekt gespeichert. Der vorherige Stand ist kein vollständiger Bearbeitungsverlauf.','Aktualisieren'],
  pt: ['Meus projetos','Novo projeto','Nome do projeto','Salvar e criar','Abrir','Renomear','Salvar nome','Cancelar','Projeto atual','Projeto sem título','Nenhum projeto salvo','Processando…','Não foi possível concluir. Verifique o salvamento e tente novamente. O conteúdo atual permanece no editor.','O projeto atual é salvo antes de criar ou trocar de projeto. Aguarde o salvamento na nuvem.','Restaurar salvamento anterior','O projeto atual é salvo antes da restauração. O salvamento anterior não é um histórico completo.','Atualizar'],
  th: ['โปรเจกต์ของฉัน','โปรเจกต์ใหม่','ชื่อโปรเจกต์','บันทึกและสร้าง','เปิด','เปลี่ยนชื่อ','บันทึกชื่อ','ยกเลิก','โปรเจกต์ปัจจุบัน','โปรเจกต์ไม่มีชื่อ','ยังไม่มีโปรเจกต์ที่บันทึก','กำลังดำเนินการ…','ดำเนินการไม่สำเร็จ ตรวจสอบสถานะการบันทึกแล้วลองอีกครั้ง เนื้อหาปัจจุบันยังอยู่ในตัวแก้ไข','จะบันทึกโปรเจกต์ปัจจุบันก่อนสร้างหรือสลับโปรเจกต์ โปรดรอให้บันทึกบนคลาวด์เสร็จ','คืนค่าการบันทึกก่อนหน้า','จะบันทึกโปรเจกต์ปัจจุบันก่อนคืนค่า การบันทึกก่อนหน้าไม่ใช่ประวัติการแก้ไขทั้งหมด','รีเฟรช'],
  vi: ['Dự án của tôi','Dự án mới','Tên dự án','Lưu và tạo','Mở','Đổi tên','Lưu tên','Hủy','Dự án hiện tại','Dự án chưa đặt tên','Chưa có dự án đã lưu','Đang xử lý…','Không thể hoàn tất. Hãy kiểm tra trạng thái lưu rồi thử lại. Nội dung hiện tại vẫn trong trình chỉnh sửa.','Dự án hiện tại được lưu trước khi tạo hoặc chuyển dự án. Hãy chờ lưu đám mây hoàn tất.','Khôi phục bản lưu trước','Dự án hiện tại được lưu trước khi khôi phục. Bản lưu trước không phải toàn bộ lịch sử chỉnh sửa.','Làm mới'],
  ru: ['Мои проекты','Новый проект','Название проекта','Сохранить и создать','Открыть','Переименовать','Сохранить имя','Отмена','Текущий проект','Проект без названия','Сохранённых проектов пока нет','Обработка…','Не удалось завершить. Проверьте статус сохранения и повторите. Текущее содержимое остаётся в редакторе.','Перед созданием или переключением текущий проект сохраняется. Дождитесь сохранения в облаке.','Восстановить предыдущее сохранение','Перед восстановлением текущий проект сохраняется. Предыдущее сохранение — не полная история изменений.','Обновить'],
  it: ['I miei progetti','Nuovo progetto','Nome del progetto','Salva e crea','Apri','Rinomina','Salva nome','Annulla','Progetto attuale','Progetto senza titolo','Nessun progetto salvato','Elaborazione…','Impossibile completare. Controlla il salvataggio e riprova. Il contenuto attuale resta nell’editor.','Il progetto attuale viene salvato prima di creare o cambiare progetto. Attendi il salvataggio nel cloud.','Ripristina salvataggio precedente','Il progetto attuale viene salvato prima del ripristino. Il salvataggio precedente non è una cronologia completa.','Aggiorna'],
  id: ['Proyek saya','Proyek baru','Nama proyek','Simpan dan buat','Buka','Ubah nama','Simpan nama','Batal','Proyek saat ini','Proyek tanpa judul','Belum ada proyek tersimpan','Memproses…','Tidak dapat menyelesaikan. Periksa status penyimpanan lalu coba lagi. Konten saat ini tetap di editor.','Proyek saat ini disimpan sebelum membuat atau beralih proyek. Tunggu penyimpanan cloud selesai.','Pulihkan simpanan sebelumnya','Proyek saat ini disimpan sebelum pemulihan. Simpanan sebelumnya bukan riwayat edit lengkap.','Muat ulang'],
};
const deletion = {
 zh: ['删除项目','删除此项目及上一份保存？删除后无法从项目列表恢复，建议先导出工程备份。','请先打开其他项目，再删除当前项目'],
 en: ['Delete project','Delete this project and its previous save? It cannot be restored from the project list. Export a backup first.','Open another project before deleting the current one'],
 ja: ['プロジェクトを削除','このプロジェクトと前回の保存を削除しますか？一覧から復元できません。先にバックアップをエクスポートしてください。','現在のプロジェクトを削除する前に別のプロジェクトを開いてください'],
 ko: ['프로젝트 삭제','이 프로젝트와 이전 저장을 삭제할까요? 목록에서 복원할 수 없습니다. 먼저 백업을 내보내세요.','현재 프로젝트를 삭제하려면 다른 프로젝트를 먼저 여세요'],
 es: ['Eliminar proyecto','¿Eliminar este proyecto y su guardado anterior? No se podrá restaurar desde la lista. Exporta una copia primero.','Abre otro proyecto antes de eliminar el actual'],
 fr: ['Supprimer le projet','Supprimer ce projet et sa sauvegarde précédente ? La restauration depuis la liste sera impossible. Exportez une sauvegarde avant.','Ouvrez un autre projet avant de supprimer le projet actuel'],
 de: ['Projekt löschen','Dieses Projekt und seinen vorherigen Stand löschen? Eine Wiederherstellung aus der Liste ist nicht möglich. Zuerst eine Sicherung exportieren.','Vor dem Löschen des aktuellen Projekts ein anderes öffnen'],
 pt: ['Excluir projeto','Excluir este projeto e seu salvamento anterior? Não será possível restaurar pela lista. Exporte uma cópia antes.','Abra outro projeto antes de excluir o atual'],
 th: ['ลบโปรเจกต์','ลบโปรเจกต์นี้และการบันทึกก่อนหน้าหรือไม่? จะกู้คืนจากรายการไม่ได้ โปรดส่งออกข้อมูลสำรองก่อน','เปิดโปรเจกต์อื่นก่อนลบโปรเจกต์ปัจจุบัน'],
 vi: ['Xóa dự án','Xóa dự án này và bản lưu trước? Không thể khôi phục từ danh sách. Hãy xuất bản sao lưu trước.','Mở dự án khác trước khi xóa dự án hiện tại'],
 ru: ['Удалить проект','Удалить этот проект и предыдущее сохранение? Восстановление из списка будет невозможно. Сначала экспортируйте резервную копию.','Перед удалением текущего проекта откройте другой'],
 it: ['Elimina progetto','Eliminare questo progetto e il salvataggio precedente? Non sarà ripristinabile dalla lista. Esporta prima una copia.','Apri un altro progetto prima di eliminare quello attuale'],
 id: ['Hapus proyek','Hapus proyek ini dan simpanan sebelumnya? Proyek tidak dapat dipulihkan dari daftar. Ekspor cadangan terlebih dahulu.','Buka proyek lain sebelum menghapus proyek saat ini'],
};
export function getAnnaProjectsCopy(language) {
  const [remove, deleteHint, deleteCurrent] = deletion[language] || deletion.en;
  return { ...Object.fromEntries(keys.map((key, index) => [key, (rows[language] || rows.en)[index]])), delete: remove, deleteHint, deleteCurrent };
}
