const rows = {
  zh: ['对话剪辑','说出你的想法，边聊边剪。','返回编辑器','例如：裁掉开头 3 秒，把背景音乐调小一点。','发送','停止','正在思考…','正在检查工程…','正在校验剪辑…','附上当前画面','将要求和工程片段信息发送给 Anna；勾选后还会发送当前画面。不会上传整段视频或音频。','变更已准备好，请审阅后应用。','未完成，请重试；工程没有被此次请求修改。','已停止。','无法读取当前画面，请取消勾选或等待画面加载。','先导入素材，再告诉我你想怎么剪。','清空对话'],
  en: ['ChatCut','Describe your idea. Edit through conversation.','Back to editor','Try: Trim the first 3 seconds and lower the music volume.','Send','Stop','Thinking…','Inspecting project…','Validating edits…','Attach current frame','Sends your request and clip information to Anna, plus the current frame if selected. Full video and audio are not uploaded.','Changes are ready. Review and apply them.','Could not finish. Retry; this request has not changed the project.','Stopped.','Current frame unavailable. Deselect it or wait for it to load.','Import media, then tell me how you want to edit.','Clear chat'],
  ja: ['対話編集','アイデアを伝えて、会話で編集。','編集画面に戻る','例：冒頭3秒をカットして音楽を小さくして。','送信','停止','考え中…','プロジェクトを確認中…','編集を検証中…','現在のフレームを添付','依頼とクリップ情報をAnnaに送信します。選択時は現在の画像も送信します。動画全体や音声は送信しません。','変更を確認して適用してください。','完了できませんでした。再試行してください。今回の依頼でプロジェクトは変更されていません。','停止しました。','画像を取得できません。選択を解除するか読み込みをお待ちください。','素材を読み込み、編集内容を伝えてください。','会話を消去'],
  ko: ['대화 편집','아이디어를 말하고 대화로 편집하세요.','편집기로 돌아가기','예: 처음 3초를 자르고 음악 볼륨을 낮춰 줘.','보내기','중지','생각 중…','프로젝트 확인 중…','편집 검증 중…','현재 화면 첨부','요청과 클립 정보를 Anna로 보냅니다. 선택하면 현재 화면도 보냅니다. 전체 영상과 오디오는 업로드하지 않습니다.','변경을 검토한 후 적용하세요.','완료하지 못했습니다. 다시 시도하세요. 이번 요청으로 프로젝트는 변경되지 않았습니다.','중지됨.','현재 화면을 읽을 수 없습니다. 선택을 해제하거나 로딩을 기다리세요.','미디어를 가져온 후 원하는 편집을 알려 주세요.','대화 지우기'],
  es: ['Edición por chat','Cuenta tu idea y edita conversando.','Volver al editor','Ejemplo: Recorta los primeros 3 segundos y baja la música.','Enviar','Detener','Pensando…','Revisando proyecto…','Validando cambios…','Adjuntar fotograma actual','Envía la solicitud y datos de clips a Anna, y el fotograma si lo seleccionas. No se suben el vídeo ni el audio completos.','Cambios listos. Revísalos y aplícalos.','No se pudo terminar. Reintenta; esta solicitud no modificó el proyecto.','Detenido.','Fotograma no disponible. Desmárcalo o espera a que cargue.','Importa contenido y dime cómo quieres editarlo.','Borrar chat'],
  fr: ['Montage par chat','Décrivez votre idée et montez en discutant.','Retour au montage','Exemple : Coupez les 3 premières secondes et baissez la musique.','Envoyer','Arrêter','Réflexion…','Vérification du projet…','Validation du montage…','Joindre l’image actuelle','Envoie la demande et les informations des clips à Anna, avec l’image si cochée. La vidéo et l’audio complets ne sont pas envoyés.','Modifications prêtes. Vérifiez-les puis appliquez-les.','Impossible de terminer. Réessayez ; cette demande n’a pas modifié le projet.','Arrêté.','Image indisponible. Décochez-la ou attendez son chargement.','Importez des médias puis décrivez votre montage.','Effacer la discussion'],
  de: ['Schnitt per Chat','Beschreibe deine Idee und schneide im Dialog.','Zurück zum Editor','Beispiel: Kürze die ersten 3 Sekunden und mache die Musik leiser.','Senden','Stoppen','Denke nach…','Prüfe Projekt…','Prüfe Änderungen…','Aktuelles Bild anhängen','Sendet Anfrage und Clipinformationen an Anna, optional das aktuelle Bild. Ganze Videos und Audios werden nicht hochgeladen.','Änderungen bereit. Prüfe sie und wende sie an.','Nicht abgeschlossen. Versuche es erneut; diese Anfrage hat das Projekt nicht geändert.','Gestoppt.','Bild nicht verfügbar. Abwählen oder auf das Laden warten.','Importiere Medien und beschreibe deinen gewünschten Schnitt.','Chat leeren'],
  pt: ['Edição por conversa','Conte sua ideia e edite conversando.','Voltar ao editor','Exemplo: Corte os primeiros 3 segundos e abaixe a música.','Enviar','Parar','Pensando…','Verificando projeto…','Validando edição…','Anexar quadro atual','Envia o pedido e informações dos clipes à Anna, com o quadro se selecionado. Não envia o vídeo ou áudio completos.','Alterações prontas. Revise e aplique.','Não foi possível concluir. Tente novamente; este pedido não alterou o projeto.','Parado.','Quadro indisponível. Desmarque ou aguarde carregar.','Importe mídia e diga como deseja editar.','Limpar conversa'],
  th: ['ตัดต่อผ่านแชต','บอกไอเดียแล้วตัดต่อผ่านบทสนทนา','กลับไปตัวแก้ไข','เช่น ตัด 3 วินาทีแรกและลดเสียงเพลง','ส่ง','หยุด','กำลังคิด…','กำลังตรวจโปรเจกต์…','กำลังตรวจการตัดต่อ…','แนบภาพปัจจุบัน','ส่งคำขอและข้อมูลคลิปไปยัง Anna พร้อมภาพปัจจุบันหากเลือก ไม่อัปโหลดวิดีโอหรือเสียงทั้งหมด','เตรียมการเปลี่ยนแปลงแล้ว ตรวจสอบก่อนนำไปใช้','ดำเนินการไม่สำเร็จ ลองอีกครั้ง คำขอนี้ยังไม่ได้เปลี่ยนโปรเจกต์','หยุดแล้ว','อ่านภาพไม่ได้ ยกเลิกการเลือกหรือรอให้โหลด','นำเข้าสื่อแล้วบอกว่าต้องการตัดต่ออย่างไร','ล้างแชต'],
  vi: ['Dựng qua trò chuyện','Nói ý tưởng, dựng qua trò chuyện.','Về trình biên tập','Ví dụ: Cắt 3 giây đầu và giảm âm lượng nhạc.','Gửi','Dừng','Đang suy nghĩ…','Đang kiểm tra dự án…','Đang xác thực chỉnh sửa…','Đính kèm khung hình hiện tại','Gửi yêu cầu và thông tin clip đến Anna, kèm khung hình nếu chọn. Không tải lên toàn bộ video hoặc âm thanh.','Thay đổi đã sẵn sàng. Xem lại rồi áp dụng.','Chưa hoàn tất. Hãy thử lại; yêu cầu này chưa thay đổi dự án.','Đã dừng.','Không đọc được khung hình. Bỏ chọn hoặc chờ tải.','Nhập nội dung rồi cho biết bạn muốn dựng thế nào.','Xóa trò chuyện'],
  ru: ['Монтаж в чате','Опишите идею и монтируйте в диалоге.','Вернуться в редактор','Например: Убери первые 3 секунды и сделай музыку тише.','Отправить','Остановить','Думаю…','Проверяю проект…','Проверяю изменения…','Прикрепить текущий кадр','Запрос и данные клипов отправляются Anna, а кадр — если выбран. Видео и аудио целиком не загружаются.','Изменения готовы. Проверьте и примените их.','Не удалось завершить. Повторите; этот запрос не изменил проект.','Остановлено.','Кадр недоступен. Снимите флажок или дождитесь загрузки.','Импортируйте медиа и опишите нужный монтаж.','Очистить чат'],
  it: ['Montaggio in chat','Racconta la tua idea e monta conversando.','Torna all’editor','Esempio: Taglia i primi 3 secondi e abbassa la musica.','Invia','Ferma','Sto pensando…','Controllo del progetto…','Verifica delle modifiche…','Allega il fotogramma attuale','Invia richiesta e dati dei clip ad Anna, più il fotogramma se selezionato. Video e audio completi non vengono caricati.','Modifiche pronte. Controllale e applicale.','Impossibile completare. Riprova; questa richiesta non ha modificato il progetto.','Fermato.','Fotogramma non disponibile. Deselezionalo o attendi il caricamento.','Importa contenuti e descrivi il montaggio desiderato.','Cancella chat'],
  id: ['Edit lewat chat','Ceritakan ide, edit lewat percakapan.','Kembali ke editor','Contoh: Potong 3 detik pertama dan kecilkan musik.','Kirim','Hentikan','Sedang berpikir…','Memeriksa proyek…','Memvalidasi edit…','Lampirkan bingkai saat ini','Mengirim permintaan dan informasi klip ke Anna, serta bingkai jika dipilih. Video dan audio lengkap tidak diunggah.','Perubahan siap. Tinjau lalu terapkan.','Belum selesai. Coba lagi; permintaan ini tidak mengubah proyek.','Dihentikan.','Bingkai tidak tersedia. Batalkan pilihan atau tunggu dimuat.','Impor media lalu jelaskan edit yang diinginkan.','Hapus chat'],
};
export function getChatCutCopy(language) {
  return Object.fromEntries(['title','hint','back','placeholder','send','stop','thinking','inspecting','validating','attach','privacy','ready','error','stopped','frameError','empty','clear'].map((key, i) => [key, (rows[language] || rows.en)[i]]));
}
